<?php

// CREARE IL PROGETTO

// APRIRE IL PROGETTO

// INSTALLIAMO LE DIPENDENZE

// FACCIAMO PARTIRE L ARTISAN PHP / NPM RUN DEV

// FACCIO PARTIRE MAMP

// VADO SU LOCALHOST

// PHPMYADMIN

// CREO IL DB

// IMPORTO IL FILE  ZIP DI OLGA

// VADO SU .ENV E IMPOSTO:

// DB_PORT = la mia port
// DB_DATABASE=books_db
// DB_PASSWORD = root

// CREO CONTROLLER CON 

// PHP ARTISAN MAKE:model Movie

// PHP ARTISAN MAKE:controller guest/PageController

// APRO HOMECONTROLLER

// CREO PUBLIC FUNCTION INDEX
// $BOOKS = BOOK::ALL();
// RETURN VIEW('HOME', COMPACT('BOOKS');

// ORA ENTRO IN ROUTES

// WEB.PHP

// E INSERISCO 

// ROUTE::GET('/' [HOMECONTROLLER::CLASS,'INDEX])->NAME('HOME');